pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
    }
}

gradle.extensions.chowlModules = [
    "core",
    "industries",
    "logistics",
    "visage",
    "test"
]

gradle.extensions.chowlModules.each { module ->
    include(module)
    project(":$module").projectDir = file("modules/$module")
}
